# How to use Pandas?
## Part - 4

In [2]:
import numpy as np
import pandas as pd

In [16]:
data = {
    'Student Name': ['Ali', 'Maryam', 'Reza', 'Sara', 'Amir', 'Zahra', 'Hossein', 'Fatemeh'],
    'Subject': ['Math', 'Physics', 'Chemistry', 'Math', 'Physics', 'Chemistry', 'Math', 'Physics'],
    'Grade': [18, 15, 19, 17, 14, 16, 20, 13],
    'Status': ['Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass']
}

df = pd.DataFrame(data)

In the following, we will discuss the process of accessing data and also changing it.

**Access** to **Rows** in a **DataFrame**

In [19]:
df.loc[1:3]

  Student Name    Subject  Grade Status
1       Maryam    Physics     15   Pass
2         Reza  Chemistry     19   Pass
3         Sara       Math     17   Pass

**Add** a **Column** in a **DataFrame**

In [20]:
df["GRE"] = [4,3,4,4,3,4,5,2]

In [21]:
df

  Student Name    Subject  Grade Status  GRE
0          Ali       Math     18   Pass    4
1       Maryam    Physics     15   Pass    3
2         Reza  Chemistry     19   Pass    4
3         Sara       Math     17   Pass    4
4         Amir    Physics     14   Pass    3
5        Zahra  Chemistry     16   Pass    4
6      Hossein       Math     20   Pass    5
7      Fatemeh    Physics     13   Pass    2

Show **General Information** of **DataFrame**

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student Name  8 non-null      str
 1   Subject       8 non-null      str
 2   Grade         8 non-null      int64
 3   Status        8 non-null      str
 4   GRE           8 non-null      int64
dtypes: int64(2), str(3)
memory usage: 452.0 bytes

Also, The ability to **Separate** also exists.

In [23]:
df[2:4]

  Student Name    Subject  Grade Status  GRE
2         Reza  Chemistry     19   Pass    4
3         Sara       Math     17   Pass    4

In [30]:
df.loc[0:2]

  Student Name    Subject  Grade Status  GRE
0          Ali       Math     18   Pass    4
1       Maryam    Physics     15   Pass    3
2         Reza  Chemistry     19   Pass    4

In [36]:
df.iloc[2]['Grade']

np.int64(19)

In [38]:
df.iloc[:,4]

0    4
1    3
2    4
3    4
4    3
5    4
6    5
7    2
Name: GRE, dtype: int64

**Essential** functions for **deleting** a **Column** or **Row**

For drop a Rows `axis=0` default.

For drop a column `axis=1`.

In [ ]:
df_test.drop('GRE', axis=1)

  Student Name    Subject  Grade Status
0          Ali       Math     18   Pass
1       Maryam    Physics     15   Pass
2         Reza  Chemistry     19   Pass
3         Sara       Math     17   Pass
4         Amir    Physics     14   Pass
5        Zahra  Chemistry     16   Pass
6      Hossein       Math     20   Pass
7      Fatemeh    Physics     13   Pass

In [ ]:
df_test.drop(2, axis=0)

  Student Name    Subject  Grade Status  GRE
0          Ali       Math     18   Pass    4
1       Maryam    Physics     15   Pass    3
3         Sara       Math     17   Pass    4
4         Amir    Physics     14   Pass    3
5        Zahra  Chemistry     16   Pass    4
6      Hossein       Math     20   Pass    5
7      Fatemeh    Physics     13   Pass    2

In [43]:
df['Sex'] = ["Male","Female","Male","Female","Male", "Female", "Male","Female"]

Data can be **Replaced**

In [45]:
df.replace("Male",'M',inplace=True)
df.replace("Female", 'F', inplace=True)

  Student Name    Subject  Grade Status  GRE Sex
0          Ali       Math     18   Pass    4   M
1       Maryam    Physics     15   Pass    3   F
2         Reza  Chemistry     19   Pass    4   M
3         Sara       Math     17   Pass    4   F
4         Amir    Physics     14   Pass    3   M
5        Zahra  Chemistry     16   Pass    4   F
6      Hossein       Math     20   Pass    5   M
7      Fatemeh    Physics     13   Pass    2   F