# How to use Pandas?
## Part - 11

In [1]:
import numpy as np
import pandas as pd

Concatenate two or more DataFrame

In [8]:
df1 = pd.DataFrame(
    {
        'A': ['A0', 'A1', 'A2', 'A3'],
        'B': ['B0', 'B1', 'B2', 'B3'],
        'C': ['C0', 'C1', 'C2', 'C3'],
        'D': ['D0', 'D1', 'D2', 'D3']
    },
    index =[0,1,2,3]
)

df2 = pd.DataFrame(
    {
        'A': ['E0', 'E1', 'E2', 'E3'],
        'B': ['F0', 'F1', 'F2', 'F3'],
        'C': ['G0', 'G1', 'G2', 'G3'],
        'D': ['H0', 'H1', 'H2', 'H3']
    },
    index =[4,5,6,7]
)

df3 = pd.DataFrame(
    {
        'A': ['I0', 'I1', 'I2', 'I3'],
        'B': ['J0', 'J1', 'J2', 'J3'],
        'C': ['K0', 'K1', 'K2', 'K3'],
        'D': ['L0', 'L1', 'L2', 'L3']
    },
    index =[8,9,10,11]
)

In [9]:
df_list = [df1, df2, df3]

In [12]:
pd.concat(df_list)

     A   B   C   D
0   A0  B0  C0  D0
1   A1  B1  C1  D1
2   A2  B2  C2  D2
3   A3  B3  C3  D3
4   E0  F0  G0  H0
5   E1  F1  G1  H1
6   E2  F2  G2  H2
7   E3  F3  G3  H3
8   I0  J0  K0  L0
9   I1  J1  K1  L1
10  I2  J2  K2  L2
11  I3  J3  K3  L3

In [20]:
pd.concat(df_list, axis=1)

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   E0   F0   G0   H0  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   E1   F1   G1   H1  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   E2   F2   G2   H2  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   E3   F3   G3   H3  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   I0   J0   K0   L0
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   I1   J1   K1   L1
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   I2   J2   K2   L2
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   I3   J3   K3   L3