# How to use Pandas?
## Part - 12

In [1]:
import numpy as np
import pandas as pd

In [2]:
Identifications_df = pd.DataFrame(
    {
        'ID': [10,20,30,40,50],
        'Name': ['Ali', 'Reza', 'Maryam', 'Mona', 'Nazanin'],
        'BYear': [1395,1375,1355,1358,1366]
    }
)

Bank_info_df = pd.DataFrame(
    {
        'ID': [10,30,40],
        'Balance': [1000,5000,3000]
    }
)

Merge two DataFrame

1. Mode:`inner`

In [3]:
pd.merge(left= Identifications_df, right=Bank_info_df, how='inner')

   ID    Name  BYear  Balance
0  10     Ali   1395     1000
1  30  Maryam   1355     5000
2  40    Mona   1358     3000

2. Mode: `left`

In [4]:
pd.merge(left= Identifications_df, right=Bank_info_df, how='left')

   ID     Name  BYear  Balance
0  10      Ali   1395   1000.0
1  20     Reza   1375      NaN
2  30   Maryam   1355   5000.0
3  40     Mona   1358   3000.0
4  50  Nazanin   1366      NaN

3. Mode:`right`

In [5]:
pd.merge(left= Identifications_df, right=Bank_info_df, how='right')

   ID    Name  BYear  Balance
0  10     Ali   1395     1000
1  30  Maryam   1355     5000
2  40    Mona   1358     3000

4. Mode:`outer`

In [ ]:
pd.merge(left= Identifications_df, right=Bank_info_df, how='outer')

   ID     Name  BYear  Balance
0  10      Ali   1395   1000.0
1  20     Reza   1375      NaN
2  30   Maryam   1355   5000.0
3  40     Mona   1358   3000.0
4  50  Nazanin   1366      NaN