# How to use Pandas?
## Part - 8

In [1]:
import numpy as np
import pandas as pd

In [2]:
tips_df = pd.read_csv("DATA/tips.csv")

In [3]:
tips_df.set_index("Payment ID", inplace=True)

In [4]:
tips_df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221

**Replace** the **Dinner** to **D** in **DataFrame**

In [5]:
tips_df.replace(to_replace='Dinner', value='D', inplace=True)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,D,2,8.49,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,D,3,3.45,Douglas Tucker,4478071379779230
Sun4458,21.01,3.50,Male,No,Sun,D,3,7.00,Travis Walters,6011812112971322
Sun5260,23.68,3.31,Male,No,Sun,D,2,11.84,Nathaniel Harris,4676137647685994
Sun2251,24.59,3.61,Female,No,Sun,D,4,6.15,Tonya Carter,4832732618637221
...,...,...,...,...,...,...,...,...,...,...
Sat2657,29.03,5.92,Male,No,Sat,D,3,9.68,Michael Avila,5296068606052842
Sat1766,27.18,2.00,Female,Yes,Sat,D,2,13.59,Monica Sanders,3506806155565404
Sat3880,22.67,2.00,Male,Yes,Sat,D,2,11.34,Keith Wong,6011891618747196
Sat17,17.82,1.75,Male,No,Sat,D,2,8.91,Dennis Dixon,4375220550950
Thur672,18.78,3.00,Female,No,Thur,D,2,9.39,Michelle Hardin,3511451626698139

**Apply** a function with single input on feature of **DataFrame**

In [6]:
tips_df['CC Number'] = tips_df['CC Number'].apply(lambda x: f'{str(x)[:4]} . . . {str(x)[-4:]}')

In [7]:
tips_df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,D,2,8.49,Christy Cunningham,3560 . . . 3410
Sun4608,10.34,1.66,Male,No,Sun,D,3,3.45,Douglas Tucker,4478 . . . 9230
Sun4458,21.01,3.50,Male,No,Sun,D,3,7.00,Travis Walters,6011 . . . 1322
Sun5260,23.68,3.31,Male,No,Sun,D,2,11.84,Nathaniel Harris,4676 . . . 5994
Sun2251,24.59,3.61,Female,No,Sun,D,4,6.15,Tonya Carter,4832 . . . 7221

**Apply** a function with **Multi** input on feature of **DataFrame**

In [8]:
def sum_pay(num1,num2):
    return num1+num2

In [9]:
tips_df['total_payment'] = tips_df.apply(lambda row: sum_pay(row['total_bill'], row['tip']), axis=1)

In [10]:
tips_df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,total_payment
Payment ID,,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,D,2,8.49,Christy Cunningham,3560 . . . 3410,18.00
Sun4608,10.34,1.66,Male,No,Sun,D,3,3.45,Douglas Tucker,4478 . . . 9230,12.00
Sun4458,21.01,3.50,Male,No,Sun,D,3,7.00,Travis Walters,6011 . . . 1322,24.51
Sun5260,23.68,3.31,Male,No,Sun,D,2,11.84,Nathaniel Harris,4676 . . . 5994,26.99
Sun2251,24.59,3.61,Female,No,Sun,D,4,6.15,Tonya Carter,4832 . . . 7221,28.20

In [11]:
def tip_calc(bill,tip):
    if tip/bill * 100 >= 25:
        return True
    else:
        return False

In [12]:
tips_df['generosity_flag'] = tips_df.apply(lambda row: tip_calc(row['total_bill'], row['tip']), axis=1)

In [13]:
tips_df[tips_df['generosity_flag'] == True].head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,total_payment,generosity_flag
Payment ID,,,,,,,,,,,,
Sun4474,10.29,2.6,Female,No,Sun,D,2,5.14,Jessica Ibarra,4999 . . . 3713,12.89,True
Sat3455,3.07,1.0,Female,Yes,Sat,D,1,3.07,Tiffany Brock,4359 . . . 5267,4.07,True
Fri6963,16.32,4.3,Female,Yes,Fri,D,2,8.16,Natalie Nguyen,5181 . . . 3396,20.62,True
Sat2614,14.31,4.0,Female,Yes,Sat,D,2,7.16,Amanda Anderson,3756 . . . 4211,18.31,True
Thur6321,7.51,2.0,Male,No,Thur,Lunch,2,3.76,Daniel Robbins,4823 . . . 1889,9.51,True

In [14]:
tips_df.drop('generosity_flag', axis=1, inplace=True)

**Other Method**

In [15]:
tips_df['generosity_flag'] = np.vectorize(tip_calc)(tips_df['total_bill'],tips_df['tip'])

In [16]:
tips_df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,total_payment,generosity_flag
Payment ID,,,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,D,2,8.49,Christy Cunningham,3560 . . . 3410,18.00,False
Sun4608,10.34,1.66,Male,No,Sun,D,3,3.45,Douglas Tucker,4478 . . . 9230,12.00,False
Sun4458,21.01,3.50,Male,No,Sun,D,3,7.00,Travis Walters,6011 . . . 1322,24.51,False
Sun5260,23.68,3.31,Male,No,Sun,D,2,11.84,Nathaniel Harris,4676 . . . 5994,26.99,False
Sun2251,24.59,3.61,Female,No,Sun,D,4,6.15,Tonya Carter,4832 . . . 7221,28.20,False