# How to use Pandas?
## Part - 5

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = {
    'Student Name': ['Ali', 'Maryam', 'Reza', 'Sara', 'Amir', 'Zahra', 'Hossein', 'Fatemeh'],
    'Subject': ['Math', 'Physics', 'Chemistry', 'Math', 'Physics', 'Chemistry', 'Math', 'Physics'],
    'Grade': [18, 15, 19, 17, 14, 16, 20, 13],
    'Status': ['Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass'],
    'Sex': ["Male","Female","Male","Female","Male", "Female", "Male","Female"]
}

df = pd.DataFrame(data)

In [6]:
df

  Student Name    Subject  Grade Status     Sex
0          Ali       Math     18   Pass    Male
1       Maryam    Physics     15   Pass  Female
2         Reza  Chemistry     19   Pass    Male
3         Sara       Math     17   Pass  Female
4         Amir    Physics     14   Pass    Male
5        Zahra  Chemistry     16   Pass  Female
6      Hossein       Math     20   Pass    Male
7      Fatemeh    Physics     13   Pass  Female

To **Replace** of the values in **DataFrame**, the method is better to other methods.

In [7]:
dic = {'Female':'F', 'Male':'M'}
df.replace(dic,inplace=True)

  Student Name    Subject  Grade Status Sex
0          Ali       Math     18   Pass   M
1       Maryam    Physics     15   Pass   F
2         Reza  Chemistry     19   Pass   M
3         Sara       Math     17   Pass   F
4         Amir    Physics     14   Pass   M
5        Zahra  Chemistry     16   Pass   F
6      Hossein       Math     20   Pass   M
7      Fatemeh    Physics     13   Pass   F

To **show** the first five rows of **DataFrame**, Use the **HEAD** Function

In [8]:
df.head()

  Student Name    Subject  Grade Status Sex
0          Ali       Math     18   Pass   M
1       Maryam    Physics     15   Pass   F
2         Reza  Chemistry     19   Pass   M
3         Sara       Math     17   Pass   F
4         Amir    Physics     14   Pass   M

To **show** the last five rows of **DataFrame**, Use the **HEAD** Function

In [9]:
df.tail()

  Student Name    Subject  Grade Status Sex
3         Sara       Math     17   Pass   F
4         Amir    Physics     14   Pass   M
5        Zahra  Chemistry     16   Pass   F
6      Hossein       Math     20   Pass   M
7      Fatemeh    Physics     13   Pass   F

To **Sort** values in **DataFrame**

If `axis=0` than sort by columns.

If `axis=1` than sort by rows.

In [11]:
df.sort_values('Sex', axis=0)

  Student Name    Subject  Grade Status Sex
1       Maryam    Physics     15   Pass   F
3         Sara       Math     17   Pass   F
5        Zahra  Chemistry     16   Pass   F
7      Fatemeh    Physics     13   Pass   F
0          Ali       Math     18   Pass   M
2         Reza  Chemistry     19   Pass   M
4         Amir    Physics     14   Pass   M
6      Hossein       Math     20   Pass   M